"""Demo-specific Pydantic schemas for Mini Demo endpoints (Marketplace).

LOCK: extra='forbid' at ALL object levels.
Any extra key at any level → 422 Unprocessable Entity.
"""

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

# ─── AI Disclosure constant (SSOT — do not duplicate) ────────────────────────
AI_DISCLOSURE = (
    "This result was generated by artificial intelligence and is provided "
    "for demonstration purposes only. It does not constitute professional advice."
)


# ─── Request schemas ──────────────────────────────────────────────────────────

class DemoReservation(BaseModel):
    """Optional reservation object. No required fields; extra keys forbidden."""
    model_config = ConfigDict(extra="forbid")


class DemoMeta(BaseModel):
    """Optional client metadata. No required fields; extra keys forbidden."""
    model_config = ConfigDict(extra="forbid")


class DemoInputs(BaseModel):
    """Required inputs block. Only 'question' is allowed."""
    model_config = ConfigDict(extra="forbid")
    question: str = Field(..., min_length=1, max_length=512)


class DemoRunCreateRequest(BaseModel):
    """POST /v1/demo/runs request body.

    HARD constraints:
    - extra keys at ANY level → 422
    - inputs.question > 512 chars → 422 (enforced by DemoInputs)
    """
    model_config = ConfigDict(extra="forbid")
    inputs: DemoInputs
    reservation: Optional[DemoReservation] = None
    meta: Optional[DemoMeta] = None
